name: Run tests
 
on:
  push:
    branches:
      - main
      - '[0-9]+.**'
    paths:
      - src/**/*.php
      - composer.json
      - .github/workflows/**
  pull_request:
    paths:
      - src/**/*.php
      - composer.json
      - .github/workflows/**

jobs:
  tests:
    name: Run tests on PHP ${{ matrix.php }} and Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.2, 8.1]
        laravel: [11.*, 10.*]
        exclude:
          - laravel: 11.*
            php: 8.1
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2
 
      - name: Run composer install
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer install --prefer-dist --no-interaction
 
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit

      - name: Run static analysis
        run: ./vendor/bin/phpstan --error-format=github